version: '3.8'

services:
  # 1. MongoDB Database
  mongo:
    image: mongo:6.0
    container_name: credia_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devadmin
      MONGO_INITDB_ROOT_PASSWORD: rahasianaufal123
    volumes:
      - credia-data:/data/db
    networks:
      - credia-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  # 2. Mongo Express GUI
  mongo-express:
    image: mongo-express
    container_name: credia_mongo_gui
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: rahasianaufal123
      ME_CONFIG_MONGODB_URL: mongodb://devadmin:rahasianaufal123@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: devadmin
      ME_CONFIG_BASICAUTH_PASSWORD: rahasianaufal123
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - credia-network

volumes:
  credia-data:

networks:
  credia-network:
    driver: bridge